export const locationState = [
  {
    fa: " مدرسه ",
    en: " School ",
    isEnabled: true,
    id: 1,
  },
  {
    fa: " هتل ",
    en: " Hotel ",
    isEnabled: true,
    id: 2,
  },
  {
    fa: " سینما ",
    en: " Cinema ",
    isEnabled: true,
    id: 3,
  },
  {
    fa: " بیمارستان ",
    en: " Hospital ",
    isEnabled: true,
    id: 4,
  },
  {
    fa: " تیمارستان ",
    en: " Mad house ",
    isEnabled: true,
    id: 5,
  },
  {
    fa: " قبرستان ",
    en: " Cemetery ",
    isEnabled: true,
    id: 6,
  },
  {
    fa: " مسجد ",
    en: " Mosque ",
    isEnabled: true,
    id: 7,
  },
  {
    fa: " سوپرمارکت ",
    en: " Super Market ",
    isEnabled: true,
    id: 8,
  },
  {
    fa: " کاباره ",
    en: " Cabaret ",
    isEnabled: true,
    id: 9,
  },
  {
    fa: " قصابی ",
    en: " Butcher Shop ",
    isEnabled: true,
    id: 10,
  },
  {
    fa: " املاکی ",
    en: " Real Estate Agency ",
    isEnabled: true,
    id: 11,
  },
  {
    fa: " بهشت ",
    en: " Paradise ",
    isEnabled: true,
    id: 12,
  },
  {
    fa: " جهنم ",
    en: " Hell ",
    isEnabled: true,
    id: 13,
  },
  {
    fa: " باغ ",
    en: " Garden ",
    isEnabled: true,
    id: 14,
  },
  {
    fa: " کاخ ",
    en: " Palace ",
    isEnabled: true,
    id: 15,
  },
  {
    fa: " استبل ",
    en: " Stable ",
    isEnabled: true,
    id: 16,
  },
  {
    fa: " مزرعه ",
    en: " Farm ",
    isEnabled: true,
    id: 17,
  },
  {
    fa: " گاوداری ",
    en: " Dairy Farm ",
    isEnabled: true,
    id: 18,
  },
  {
    fa: " گل فروشی ",
    en: " Florist ",
    isEnabled: true,
    id: 19,
  },
  {
    fa: " داروخانه ",
    en: " Pharmacy ",
    isEnabled: true,
    id: 20,
  },
  {
    fa: " خانه سالمندان ",
    en: " Old People's Home ",
    isEnabled: true,
    id: 21,
  },
  {
    fa: " دانشگاه ",
    en: " University ",
    isEnabled: true,
    id: 22,
  },
  {
    fa: " دادگاه ",
    en: " Court ",
    isEnabled: true,
    id: 23,
  },
  {
    fa: " زیردریایی ",
    en: " Submarine ",
    isEnabled: true,
    id: 24,
  },
  {
    fa: " رستوران ",
    en: " Restaurant ",
    isEnabled: true,
    id: 25,
  },
  {
    fa: " بانک ",
    en: " Bank ",
    isEnabled: true,
    id: 26,
  },
  {
    fa: " استخر ",
    en: " Swimming Pool ",
    isEnabled: true,
    id: 27,
  },
  {
    fa: " دستشویی ",
    en: " WC ",
    isEnabled: true,
    id: 28,
  },
  {
    fa: " باغ وحش ",
    en: " Zoo ",
    isEnabled: true,
    id: 29,
  },
  {
    fa: " آزمایشگاه ",
    en: " Laboratory ",
    isEnabled: true,
    id: 30,
  },
  {
    fa: " جنگل ",
    en: " Jungle ",
    isEnabled: true,
    id: 31,
  },
  {
    fa: " دریا ",
    en: " Sea ",
    isEnabled: true,
    id: 32,
  },
  {
    fa: " اقیانوس ",
    en: " Ocean ",
    isEnabled: true,
    id: 33,
  },
  {
    fa: " صحرا ",
    en: " Desert ",
    isEnabled: true,
    id: 34,
  },
  {
    fa: " خشکشویی ",
    en: " Laundry ",
    isEnabled: true,
    id: 35,
  },
  {
    fa: " کتاب فروشی ",
    en: " Book Store ",
    isEnabled: true,
    id: 36,
  },
  {
    fa: " صرافی ",
    en: " Exchange ",
    isEnabled: true,
    id: 37,
  },
  {
    fa: " آشپزخانه ",
    en: " kitchen ",
    isEnabled: true,
    id: 38,
  },
  {
    fa: " پادگان ",
    en: " Barracks ",
    isEnabled: true,
    id: 39,
  },
  {
    fa: " فرودگاه ",
    en: " Airport ",
    isEnabled: true,
    id: 40,
  },
  {
    fa: " شهربازی ",
    en: " Amusement Park ",
    isEnabled: true,
    id: 41,
  },
  {
    fa: " پارک ",
    en: " Park ",
    isEnabled: true,
    id: 42,
  },
  {
    fa: " کوه ",
    en: " Mountain ",
    isEnabled: true,
    id: 43,
  },
  {
    fa: " باشگاه بدنسازی ",
    en: " Body Building Club ",
    isEnabled: true,
    id: 44,
  },
  {
    fa: " استادیوم ",
    en: " Stadium ",
    isEnabled: true,
    id: 45,
  },
  {
    fa: " کلیسا ",
    en: " Church ",
    isEnabled: true,
    id: 46,
  },
  {
    fa: " آرایشگاه ",
    en: " Hairdresser's ",
    isEnabled: true,
    id: 47,
  },
  {
    fa: " تالار عروسی ",
    en: " Wedding Forum ",
    isEnabled: true,
    id: 48,
  },
  {
    fa: " سیرک ",
    en: " Circus ",
    isEnabled: true,
    id: 49,
  },
  {
    fa: " موزه ",
    en: " Museum ",
    isEnabled: true,
    id: 50,
  },
  {
    fa: " تعمیرگاه ",
    en: " Repair Shop ",
    isEnabled: true,
    id: 51,
  },
  {
    fa: " ساحل ",
    en: " Beach ",
    isEnabled: true,
    id: 52,
  },
  {
    fa: " آسیا ",
    en: " Asia ",
    isEnabled: true,
    id: 53,
  },
  {
    fa: " اروپا ",
    en: " Europe ",
    isEnabled: true,
    id: 54,
  },
  {
    fa: " آمریکا ",
    en: " America ",
    isEnabled: true,
    id: 55,
  },
  {
    fa: " آفریقا ",
    en: " Africa ",
    isEnabled: true,
    id: 56,
  },
  {
    fa: " قطب جنوب ",
    en: " South Pole ",
    isEnabled: true,
    id: 57,
  },
  {
    fa: " مترو ",
    en: " Metro ",
    isEnabled: true,
    id: 58,
  },
  {
    fa: " دامپزشکی ",
    en: " Veterinary ",
    isEnabled: true,
    id: 59,
  },
  {
    fa: " کلوب شبانه ",
    en: " Night Club ",
    isEnabled: true,
    id: 60,
  },
  {
    fa: " پمپ بنزین ",
    en: " Gas Station ",
    isEnabled: true,
    id: 61,
  },
  {
    fa: " کفاشی ",
    en: " Shoemaker ",
    isEnabled: true,
    id: 62,
  },
  {
    fa: " دندان پزشکی ",
    en: " Dental ",
    isEnabled: true,
    id: 63,
  },
  {
    fa: " خوابگاه ",
    en: " Dorm ",
    isEnabled: true,
    id: 64,
  },
  {
    fa: " خونه ",
    en: " Home ",
    isEnabled: true,
    id: 65,
  },
]